/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int HEX_LITERAL = 9;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 10;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 11;
  /** RegularExpression Id. */
  int EXPONENT = 12;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 13;
  /** RegularExpression Id. */
  int STRING_LITERAL = 14;
  /** RegularExpression Id. */
  int AUTO = 15;
  /** RegularExpression Id. */
  int REGISTER = 16;
  /** RegularExpression Id. */
  int STATIC = 17;
  /** RegularExpression Id. */
  int EXTERN = 18;
  /** RegularExpression Id. */
  int TYPEDEF = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int SHORT = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int LONG = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int SIGNED = 27;
  /** RegularExpression Id. */
  int UNSIGNED = 28;
  /** RegularExpression Id. */
  int CONST = 29;
  /** RegularExpression Id. */
  int VOLATILE = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int DFLT = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int SWITCH = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int FOR = 37;
  /** RegularExpression Id. */
  int DO = 38;
  /** RegularExpression Id. */
  int GOTO = 39;
  /** RegularExpression Id. */
  int CONTINUE = 40;
  /** RegularExpression Id. */
  int BREAK = 41;
  /** RegularExpression Id. */
  int RETURN = 42;
  /** RegularExpression Id. */
  int ENUM = 43;
  /** RegularExpression Id. */
  int SIZEOF = 44;
  /** RegularExpression Id. */
  int STRUCT = 45;
  /** RegularExpression Id. */
  int UNION = 46;
  /** RegularExpression Id. */
  int PRINT = 47;
  /** RegularExpression Id. */
  int SCAN = 48;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 49;
  /** RegularExpression Id. */
  int LETRA = 50;
  /** RegularExpression Id. */
  int DIGITO = 51;
  /** RegularExpression Id. */
  int AC = 52;
  /** RegularExpression Id. */
  int FC = 53;
  /** RegularExpression Id. */
  int AP = 54;
  /** RegularExpression Id. */
  int FP = 55;
  /** RegularExpression Id. */
  int PV = 56;
  /** RegularExpression Id. */
  int P = 57;
  /** RegularExpression Id. */
  int ACO = 58;
  /** RegularExpression Id. */
  int FCO = 59;
  /** RegularExpression Id. */
  int VIRGULA = 60;
  /** RegularExpression Id. */
  int IGUAL = 61;
  /** RegularExpression Id. */
  int INCREMENTO = 62;
  /** RegularExpression Id. */
  int DECREMENTO = 63;
  /** RegularExpression Id. */
  int MAIORIGUAL = 64;
  /** RegularExpression Id. */
  int MENORIGUAL = 65;
  /** RegularExpression Id. */
  int MAIOR = 66;
  /** RegularExpression Id. */
  int MENOR = 67;
  /** RegularExpression Id. */
  int IGUALIGUAL = 68;
  /** RegularExpression Id. */
  int DIFERENTE = 69;
  /** RegularExpression Id. */
  int SOMA = 70;
  /** RegularExpression Id. */
  int SUBTRACAO = 71;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 72;
  /** RegularExpression Id. */
  int DIVISAO = 73;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"auto\"",
    "\"register\"",
    "\"static\"",
    "\"extern\"",
    "\"typedef\"",
    "\"void\"",
    "\"char\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"const\"",
    "\"volatile\"",
    "\"case\"",
    "\"default\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"while\"",
    "\"for\"",
    "\"do\"",
    "\"goto\"",
    "\"continue\"",
    "\"break\"",
    "\"return\"",
    "\"enum\"",
    "\"sizeof\"",
    "\"struct\"",
    "\"union\"",
    "\"printf\"",
    "\"scanf\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"&\"",
    "\"~\"",
    "\"!\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"<<\"",
    "\">>\"",
    "\"%\"",
  };

}
